### ISSUE TITLE
Error after submit hash

### ISSUE THREAD

**Issue by ghost** [carbonblack/cb-virustotal-connector#5]
after installed the cb-virustotal and the service running and the conf file add the needs, i got this error

ERROR: Temporary error analyzing md5sum D5E1DA45D515B5746AA91E066B942642: Exception in check_result_for (Traceback (most recent call last):
  File "site-packages/cbint/utils/detonation/binary_analysis.py", line 260, in quick_scan
  File "cbopensource/connectors/virustotal/bridge.py", line 60, in check_result_for
  File "cbopensource/connectors/virustotal/apiclient_virustotal.py", line 65, in get_report
  File "site-packages/requests/sessions.py", line 537, in get
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 516, in send
ConnectionError: HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?apikey=[I remove it]&resource=D5E1DA45D515B5746AA91E066B942642 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f65e35ebd90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
). Will retry in 60 seconds.
2021-03-21 14:17:43,794: binary_analysis: ERROR: Temporary error analyzing md5sum 1E808F4DA9ADAAB60409380C662467E8: Exception in check_result_for (Traceback (most recent call last):
  File "site-packages/cbint/utils/detonation/binary_analysis.py", line 260, in quick_scan
  File "cbopensource/connectors/virustotal/bridge.py", line 60, in check_result_for
  File "cbopensource/connectors/virustotal/apiclient_virustotal.py", line 65, in get_report
  File "site-packages/requests/sessions.py", line 537, in get
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 516, in send
ConnectionError: HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?apikey=[I remove it]&resource=1E808F4DA9ADAAB60409380C662467E8 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f65e35eb850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
). Will retry in 60 seconds.
Can any one Help

**Comment by JakeysQ** [comment]
Do you access via a proxy server?
